# Run general classifier for 'study type' classification of articles

- For further information, please refer to https://pypi.org/project/general-classifier/#4-evaluate-prompt-performance
- Load dataset and install necessary libraries
- Prepare dataset, i.e., drop irrelevant columns and merge "PaperTitle" and "Abstract"
- Set up general classifier (gc), load categories and define prompt
- Define LLM to use
- Run gc on dataset 
- Evaluate performance
- Merge with initial dataset

## 1) Set up libraries and datasets

In [ ]:
# Install libraries
!pip install guidance
!pip install pydantic --upgrade
!pip install openai
!pip install general-classifier
print("Success!")

In [1]:
# Import libraries
import os
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import time
import re
from tqdm import tqdm
import csv
import general_classifier
from general_classifier import gc
import csv
import transformers
import re
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoModelForSeq2SeqLM, TextStreamer
import torch
import requests
import sentencepiece as spm
import time
import json
import torch
import ast
import openai
from openai import OpenAI

print("Success!")

Success!

In [2]:
from dotenv import load_dotenv

load_dotenv()  # loads variables from file .env

# Set the working directory and file paths
input_directory = "." #os.getenv("INPUT_DIRECTORY")
output_directory = os.getenv("OUTPUT_DIRECTORY")
classifier_directory = os.getenv("CLASSIFIER_DIRECTORY")
api_key = os.getenv("OPENAI_API_KEY")

# Change the working directory
#os.chdir(classifier_directory)
print("Current Working Directory:", os.getcwd())

Current Working Directory: /Users/andreiblindu/Desktop/Idiap/code/Variantscape/notebooks/04_categorization

In [3]:
# Load topics and categories
os.chdir(input_directory)
print("Current Working Directory:", os.getcwd())

#topics_and_categories = pd.read_csv("studydesign.csv")
#categories = topics_and_categories.iloc[:, 0].dropna().tolist()
categories = list(set(pd.read_csv("study_classification_output.csv")['Study_design']))

print("--> Topics and categories loaded!")

# Load dataset to run classifier
os.chdir(output_directory)
print("\nCurrent Working Directory:", os.getcwd())

cancer_df = pd.read_csv("binary_cancer_matrix_filtered.csv")
len_cancer_df=len(cancer_df)
print(f" --> Total rows in cancer dataset: {len_cancer_df:,}")

cancer_df = cancer_df[['PaperId', 'PaperTitle', 'Abstract']].copy()
print("\n\nSuccess!")

os.chdir(classifier_directory)
print("Current Working Directory:", os.getcwd())

Current Working Directory: /Users/andreiblindu/Desktop/Idiap/code/Variantscape/notebooks/04_categorization
--> Topics and categories loaded!

Current Working Directory: /Users/andreiblindu/Desktop/Idiap/code/Variantscape/results_openalex/04_categorization
 --> Total rows in cancer dataset: 14,500


Success!
Current Working Directory: /Users/andreiblindu/Desktop/Idiap/code/Variantscape/results_openalex/04_03_classifier

## 2) Set up general calssifier

In [4]:
# Setup gc
gc.setModel(newModel="meta-llama/Llama-3.3-70B-Instruct", newModelType="DeepInfra", newInferenceType="cloud", api_key=api_key) #api_key="API_KEY")
print("Success!")

Success!

In [5]:
gc.removeAllTopics()
gc.add_topic(
    topic_name="Study Type",
    categories=categories 
)
# Display all defined topics and their categories
gc.show_topics_and_categories()

All topics have been removed, counters reset, and related data cleared.
Topic 1 (ID=A): Study Type
  Prompt: INSTRUCTION: You are a helpful classifier. You select the correct of the possible categories for classifying a piece of text. The topic of the classification is '[TOPIC]'. The allowed categories are '[CATEGORIES]'. QUESTION: The text to be classified is '[TEXT]'. ANSWER: The correct category for this text is '
    1. In vivo/Animal study (ID=a)
    2. In silico study (ID=b)
    3. Systematic review study (ID=c)
    4. In vitro study (ID=d)
    5. undefined (ID=e)
    6. Observational/RWE study (ID=f)
    7. Case report study (ID=g)
    8. Clinical study (ID=h)

In [6]:
gc.setPrompt(
    topicId="A", 
    newPrompt=(
        "Prompt: INSTRUCTION: You are a helpful classifier. You are given the abstract of a "
        "scientific, biomedical publication and you have to select the correct of the possible categories. "
        "The topic of the classification is '[TOPIC]'. The allowed categories are '[CATEGORIES]'. "
        "QUESTION: The abstract to be classified is '[TEXT]'. "
        'ANSWER: The correct category for this abstract is "".'
    )
)

Prompt for topic ID A updated.

In [7]:
# Show prompt and topic with associated categories
gc.show_topics_and_categories()

Topic 1 (ID=A): Study Type
  Prompt: Prompt: INSTRUCTION: You are a helpful classifier. You are given the abstract of a scientific, biomedical publication and you have to select the correct of the possible categories. The topic of the classification is '[TOPIC]'. The allowed categories are '[CATEGORIES]'. QUESTION: The abstract to be classified is '[TEXT]'. ANSWER: The correct category for this abstract is "".
    1. In vivo/Animal study (ID=a)
    2. In silico study (ID=b)
    3. Systematic review study (ID=c)
    4. In vitro study (ID=d)
    5. undefined (ID=e)
    6. Observational/RWE study (ID=f)
    7. Case report study (ID=g)
    8. Clinical study (ID=h)

## 3) Run general classifier

In [ ]:
##### Create a article subset, remove everything except the column to classify and the PaperID
subset_df = cancer_df # Update-AB: added

# Create the new column by combining "PaperTitle" and "Abstract"
subset_df["PaperTitle_and_Abstracts"] = subset_df["PaperTitle"].astype(str) + " " + subset_df["Abstract"].astype(str)

# Keep only the required columns
subset_df_gccolumn = subset_df[["PaperId", "PaperTitle_and_Abstracts"]].copy()

# Generate output
csv_path = "subset_df_gccolumn.csv"
subset_df_gccolumn.to_csv(csv_path, index=False)
print(f"File saved: {csv_path}")
print(subset_df_gccolumn.head(20))
print("Length of dataset:",len(subset_df_gccolumn))

File saved: subset_df_gccolumn.csv
       PaperId                           PaperTitle_and_Abstracts
0   7106250716  PVNDMVLiver Circuit Drives Hepatocellular Carc...
1   7119160011  Screening and biological function analysis of ...
2   7125102904  Recent advances in non-alcoholic steatohepatit...
3   7125105582  Complete response to BRICS in Locally advanced...
4   7125132542  Diagnostic value of interleukin-8 in colon can...
5   7125157184  The assessment of the potential anti-tumor eff...
6   7125166668  Functions of Glucocorticoids in Breast and Oth...
7   7125167036  Two-Stage Microwave Hyperthermia Using Magneti...
8   7125201640  Clinicopathological Factors on Survival after ...
9   7125210125  FBXO9 promotes anti-tumor immunity via degrada...
10  7125220741  Macrophage-derived CTSZ promotes prostate canc...
11  7125230579  MIG-6 Regulates HDAC1-Mediated Angiogenesis an...
12  7125244721  The Interplay Between Cellular Senescence and ...
13  7125246792  Design, synthesis, and preliminary antitumor m...
14  7125250818  Knockdown of 5-methylcytosine RNA methyltransf...
15  7125252819  A monocyte-derived blood transcriptomic signat...
16  7125263113  SIAH2WNK1 Signaling Drives Glycolytic Metaboli...
17  7125273960  The miR-142-5p overexpression induces cell cyc...
18  7125279505  Male Breast Cancer in Serbia: A 33-Year Retros...
19  7124836033  Omission of axillary lymph node dissection in ...
Length of dataset: 14500

In [ ]:
# Run classification on the subset CSV file
os.chdir(classifier_directory) #os.chdir(output_directory)
start_time = time.time()

'''gc.classify_table(dataset="subset_df_gccolumn", withEvaluation=False, constrainedOutput=True)
# withEvaluation=False if not done manually
print("Success!")'''
# Update-AB: added multi threading
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor
import time

df = subset_df_gccolumn
num_workers = 8   # 4–8 is usually safe

chunks = [df.iloc[i::num_workers] for i in range(num_workers)]

for c in chunks:
    print(len(c))

1813
1813
1813
1813
1812
1812
1812
1812

In [ ]:
# Run classification on the subset CSV file
os.chdir(classifier_directory) #os.chdir(output_directory)
start_time = time.time()

'''gc.classify_table(dataset="subset_df_gccolumn", withEvaluation=False, constrainedOutput=True)
# withEvaluation=False if not done manually
print("Success!")'''
# Update-AB: added multi threading
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor
import time

df = subset_df_gccolumn
num_workers = 8   # 4–8 is usually safe

chunks = [df.iloc[i::num_workers] for i in range(num_workers)]

def classify_chunk(chunk, i):
    dataset_name = f"chunk_{i+1}"
    chunk.to_csv(dataset_name + ".csv", index=False)

    gc.classify_table(
        dataset=dataset_name,
        withEvaluation=False,
        constrainedOutput=True
    )
    return dataset_name


start_time = time.time()

with ThreadPoolExecutor(max_workers=num_workers) as executor:
    futures = [executor.submit(classify_chunk, chunk, i)
               for i, chunk in enumerate(chunks)]
    
    results = [f.result() for f in futures]

print("Success!")
print("Chunks processed:", results)

print("Runtime:", time.time() - start_time)
###################


# Get end timestamp
end_time = time.time()
runtime_duration = end_time - start_time
output_filename = f"Study_design_classification_runtime_subset_data.txt"

os.chdir(output_directory)
with open(output_filename, "w") as f:
    f.write(f"Start Time: {time.ctime(start_time)}\n")
    f.write(f"End Time: {time.ctime(end_time)}\n")
    f.write(f"Total Runtime (seconds): {runtime_duration:.4f}\n")
print(f"Runtime saved in {output_filename}")

Processed 100/1813 rows (5.52%)
Processed 100/1813 rows (5.52%)
Processed 100/1812 rows (5.52%)Processed 100/1812 rows (5.52%)

Processed 100/1812 rows (5.52%)
Processed 100/1812 rows (5.52%)
Processed 100/1812 rows (5.52%)
Processed 100/1812 rows (5.52%)
Processed 200/1813 rows (11.03%)
Processed 200/1812 rows (11.04%)
Processed 200/1812 rows (11.04%)
Processed 200/1812 rows (11.04%)
Processed 200/1813 rows (11.03%)
Processed 200/1812 rows (11.04%)
Processed 200/1812 rows (11.04%)
Processed 200/1812 rows (11.04%)
Processed 300/1812 rows (16.56%)
Processed 300/1813 rows (16.55%)
Processed 300/1812 rows (16.56%)
Processed 300/1812 rows (16.56%)
Processed 300/1812 rows (16.56%)
Processed 300/1813 rows (16.55%)
Processed 300/1812 rows (16.56%)
Processed 300/1812 rows (16.56%)
Processed 400/1812 rows (22.08%)
Processed 400/1813 rows (22.06%)
Processed 400/1812 rows (22.08%)
Processed 400/1812 rows (22.08%)
Processed 400/1812 rows (22.08%)
Processed 400/1812 rows (22.08%)
Processed 400/1813 rows (22.06%)
Processed 400/1812 rows (22.08%)
Processed 500/1813 rows (27.58%)
Processed 500/1812 rows (27.59%)
Processed 500/1813 rows (27.58%)
Processed 500/1812 rows (27.59%)
Processed 500/1812 rows (27.59%)
Processed 500/1812 rows (27.59%)
Processed 500/1812 rows (27.59%)
Processed 500/1812 rows (27.59%)
Processed 600/1813 rows (33.09%)Processed 600/1812 rows (33.11%)

Processed 600/1813 rows (33.09%)
Processed 600/1812 rows (33.11%)
Processed 600/1812 rows (33.11%)
Processed 600/1812 rows (33.11%)
Processed 600/1812 rows (33.11%)
Processed 600/1812 rows (33.11%)
Processed 700/1812 rows (38.63%)Processed 700/1813 rows (38.61%)

Processed 700/1812 rows (38.63%)
Processed 700/1813 rows (38.61%)
Processed 700/1812 rows (38.63%)
Processed 700/1812 rows (38.63%)
Processed 700/1812 rows (38.63%)
Processed 700/1812 rows (38.63%)
Processed 800/1812 rows (44.15%)
Processed 800/1812 rows (44.15%)Processed 800/1813 rows (44.13%)

Processed 800/1813 rows (44.13%)
Processed 800/1812 rows (44.15%)
Processed 800/1812 rows (44.15%)
Processed 800/1812 rows (44.15%)
Processed 800/1812 rows (44.15%)
Processed 900/1813 rows (49.64%)
Processed 900/1812 rows (49.67%)
Processed 900/1813 rows (49.64%)
Processed 900/1812 rows (49.67%)
Processed 900/1812 rows (49.67%)
Processed 900/1812 rows (49.67%)
Processed 900/1812 rows (49.67%)
Processed 900/1812 rows (49.67%)
Processed 1000/1812 rows (55.19%)
Processed 1000/1813 rows (55.16%)
Processed 1000/1812 rows (55.19%)
Processed 1000/1812 rows (55.19%)
Processed 1000/1813 rows (55.16%)
Processed 1000/1812 rows (55.19%)
Processed 1000/1812 rows (55.19%)
Processed 1000/1812 rows (55.19%)
Processed 1100/1812 rows (60.71%)
Processed 1100/1813 rows (60.67%)
Processed 1100/1812 rows (60.71%)
Processed 1100/1812 rows (60.71%)Processed 1100/1812 rows (60.71%)

Processed 1100/1813 rows (60.67%)
Processed 1100/1812 rows (60.71%)
Processed 1100/1812 rows (60.71%)
Processed 1200/1812 rows (66.23%)
Processed 1200/1812 rows (66.23%)
Processed 1200/1813 rows (66.19%)
Processed 1200/1812 rows (66.23%)
Processed 1200/1812 rows (66.23%)
Processed 1200/1812 rows (66.23%)
Processed 1200/1812 rows (66.23%)
Processed 1200/1813 rows (66.19%)
Processed 1300/1812 rows (71.74%)
Processed 1300/1812 rows (71.74%)
Processed 1300/1813 rows (71.70%)
Processed 1300/1812 rows (71.74%)
Processed 1300/1812 rows (71.74%)
Processed 1300/1812 rows (71.74%)
Processed 1300/1813 rows (71.70%)
Processed 1300/1812 rows (71.74%)
Processed 1400/1812 rows (77.26%)
Processed 1400/1812 rows (77.26%)
Processed 1400/1813 rows (77.22%)
Processed 1400/1812 rows (77.26%)
Processed 1400/1812 rows (77.26%)
Processed 1400/1812 rows (77.26%)
Processed 1400/1813 rows (77.22%)
Processed 1400/1812 rows (77.26%)
Processed 1500/1812 rows (82.78%)
Processed 1500/1813 rows (82.74%)
Processed 1500/1812 rows (82.78%)
Processed 1500/1812 rows (82.78%)
Processed 1500/1812 rows (82.78%)
Processed 1500/1812 rows (82.78%)
Processed 1500/1813 rows (82.74%)
Processed 1500/1812 rows (82.78%)
Processed 1600/1812 rows (88.30%)
Processed 1600/1813 rows (88.25%)
Processed 1600/1812 rows (88.30%)
Processed 1600/1812 rows (88.30%)
Processed 1600/1812 rows (88.30%)
Processed 1600/1812 rows (88.30%)
Processed 1600/1813 rows (88.25%)
Processed 1600/1812 rows (88.30%)
Processed 1700/1812 rows (93.82%)
Processed 1700/1813 rows (93.77%)
Processed 1700/1812 rows (93.82%)
Processed 1700/1812 rows (93.82%)
Processed 1700/1812 rows (93.82%)
Processed 1700/1812 rows (93.82%)
Processed 1700/1813 rows (93.77%)
Processed 1700/1812 rows (93.82%)
Processed 1800/1812 rows (99.34%)
Processed 1800/1812 rows (99.34%)
Processed 1800/1813 rows (99.28%)
Processed 1800/1812 rows (99.34%)
Processed 1800/1812 rows (99.34%)
Processed 1800/1812 rows (99.34%)
Processed 1800/1813 rows (99.28%)
Processed 1800/1812 rows (99.34%)
Processed 1812/1812 rows (100.00%)
Classification of 'chunk_1.csv' complete. Output written to 'chunk_1_(result).csv'.
Elapsed time: 2806.61 seconds
Processed 1812/1812 rows (100.00%)
Classification of 'chunk_4.csv' complete. Output written to 'chunk_4_(result).csv'.
Elapsed time: 2808.68 seconds
Processed 1812/1812 rows (100.00%)
Classification of 'chunk_7.csv' complete. Output written to 'chunk_7_(result).csv'.
Elapsed time: 2808.76 seconds
Processed 1812/1812 rows (100.00%)
Classification of 'chunk_3.csv' complete. Output written to 'chunk_3_(result).csv'.
Elapsed time: 2809.65 seconds
Processed 1813/1813 rows (100.00%)
Classification of 'chunk_2.csv' complete. Output written to 'chunk_2_(result).csv'.
Elapsed time: 2809.60 seconds
Processed 1812/1812 rows (100.00%)
Classification of 'chunk_5.csv' complete. Output written to 'chunk_5_(result).csv'.
Elapsed time: 2812.42 seconds
Processed 1812/1812 rows (100.00%)
Classification of 'chunk_6.csv' complete. Output written to 'chunk_6_(result).csv'.
Elapsed time: 2818.13 seconds
Processed 1813/1813 rows (100.00%)
Classification of 'chunk_0.csv' complete. Output written to 'chunk_0_(result).csv'.
Elapsed time: 2820.03 seconds
Success!
Chunks processed: ['chunk_0', 'chunk_1', 'chunk_2', 'chunk_3', 'chunk_4', 'chunk_5', 'chunk_6', 'chunk_7']
Runtime: 2820.313749074936
Runtime saved in Study_design_classification_runtime_subset_data.txt

In [ ]:
## Again for debug

# Run classification on the subset CSV file
os.chdir(classifier_directory) #os.chdir(output_directory)
start_time = time.time()

'''gc.classify_table(dataset="subset_df_gccolumn", withEvaluation=False, constrainedOutput=True)
# withEvaluation=False if not done manually
print("Success!")'''
# Update-AB: added multi threading
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor
import time

df = subset_df_gccolumn
num_workers = 8   # 4–8 is usually safe

chunks = [df.iloc[i::num_workers] for i in range(num_workers)]

def classify_chunk(chunk, i):
    dataset_name = f"chunk_{i+1}"
    chunk.to_csv(dataset_name + ".csv", index=False)

    gc.classify_table(
        dataset=dataset_name,
        withEvaluation=False,
        constrainedOutput=True
    )
    return dataset_name


start_time = time.time()

with ThreadPoolExecutor(max_workers=num_workers) as executor:
    futures = [executor.submit(classify_chunk, chunk, i)
               for i, chunk in enumerate(chunks)]
    
    results = [f.result() for f in futures]

print("Success!")
print("Chunks processed:", results)

print("Runtime:", time.time() - start_time)
###################


# Get end timestamp
end_time = time.time()
runtime_duration = end_time - start_time
output_filename = f"Study_design_classification_runtime_subset_data.txt"

os.chdir(output_directory)
with open(output_filename, "w") as f:
    f.write(f"Start Time: {time.ctime(start_time)}\n")
    f.write(f"End Time: {time.ctime(end_time)}\n")
    f.write(f"Total Runtime (seconds): {runtime_duration:.4f}\n")
print(f"Runtime saved in {output_filename}")

## 4) Batch running of general calssifier

In [9]:
subset_df=cancer_df.copy()
print(f"Length of cancer dataset to process in batches: {len(subset_df):,}")

Length of cancer dataset to process in batches: 14,500

In [ ]:
# Create a new column by combining "PaperTitle" and "Abstract"

subset_df["PaperTitle_and_Abstracts"] = subset_df["PaperTitle"].astype(str) + " " + subset_df["Abstract"].astype(str)
subset_df_gccolumn = subset_df[["PaperId", "PaperTitle_and_Abstracts"]].copy()

# Change the working directory
#classifier_directory = ""
os.chdir(classifier_directory)
print("Current Working Directory:", os.getcwd())

# Save the full newly created dataset as CSV
csv_path = "subset_df_gccolumn.csv"
subset_df_gccolumn.to_csv(csv_path, index=False)

# Print confirmation and show first rows
print(f"File saved: {classifier_directory}")
print(subset_df_gccolumn.head(20))
print("\n\nLength of dataset:", len(subset_df_gccolumn))

# ---- Dynamically Create Batches ----
# Define batch size
batch_size = 4000 #50000 --> Update-AB: is too big, I try with smaller
total_batches = (len(subset_df_gccolumn) + batch_size - 1) // batch_size
print(f"\n\nTotal number of batches: {total_batches}")


# Split dataset into batches and save them
for batch_num in range(total_batches):
    start_idx = batch_num * batch_size
    end_idx = min(start_idx + batch_size, len(subset_df_gccolumn))
    batch_df = subset_df_gccolumn.iloc[start_idx:end_idx]
    batch_filename = os.path.join(classifier_directory, f"subset_df_gccolumn_batch_{batch_num+1}.csv")
    batch_df.to_csv(batch_filename, index=False)
    print(f"Batch {batch_num+1}/{total_batches} saved: {batch_filename} | Articles in batch: {len(batch_df)}")

Current Working Directory: /Users/andreiblindu/Desktop/Idiap/code/Variantscape/results_openalex/04_03_classifier
File saved: ../../results_openalex/04_03_classifier
       PaperId                           PaperTitle_and_Abstracts
0   7106250716  PVNDMVLiver Circuit Drives Hepatocellular Carc...
1   7119160011  Screening and biological function analysis of ...
2   7125102904  Recent advances in non-alcoholic steatohepatit...
3   7125105582  Complete response to BRICS in Locally advanced...
4   7125132542  Diagnostic value of interleukin-8 in colon can...
5   7125157184  The assessment of the potential anti-tumor eff...
6   7125166668  Functions of Glucocorticoids in Breast and Oth...
7   7125167036  Two-Stage Microwave Hyperthermia Using Magneti...
8   7125201640  Clinicopathological Factors on Survival after ...
9   7125210125  FBXO9 promotes anti-tumor immunity via degrada...
10  7125220741  Macrophage-derived CTSZ promotes prostate canc...
11  7125230579  MIG-6 Regulates HDAC1-Mediated Angiogenesis an...
12  7125244721  The Interplay Between Cellular Senescence and ...
13  7125246792  Design, synthesis, and preliminary antitumor m...
14  7125250818  Knockdown of 5-methylcytosine RNA methyltransf...
15  7125252819  A monocyte-derived blood transcriptomic signat...
16  7125263113  SIAH2WNK1 Signaling Drives Glycolytic Metaboli...
17  7125273960  The miR-142-5p overexpression induces cell cyc...
18  7125279505  Male Breast Cancer in Serbia: A 33-Year Retros...
19  7124836033  Omission of axillary lymph node dissection in ...


Length of dataset: 14500


Total number of batches: 4
Batch 1/4 saved: ../../results_openalex/04_03_classifier/subset_df_gccolumn_batch_1.csv | Articles in batch: 4000
Batch 2/4 saved: ../../results_openalex/04_03_classifier/subset_df_gccolumn_batch_2.csv | Articles in batch: 4000
Batch 3/4 saved: ../../results_openalex/04_03_classifier/subset_df_gccolumn_batch_3.csv | Articles in batch: 4000
Batch 4/4 saved: ../../results_openalex/04_03_classifier/subset_df_gccolumn_batch_4.csv | Articles in batch: 2500

In [11]:
# Batch processing

# Manually define the current batch to process!
n = 1  # Define the current batch number manually!!!!
# if new running
lastprocessedbatch=0
total_batches=4
batch_size = 4000

# Check if n and last processed batch are the same
if n == lastprocessedbatch:
    print("\n !!! UPDATE BATCH NUMBER WARNING !!!")
    print(f"The current batch number ({n}) is the same as the last processed batch ({lastprocessedbatch}).")
    print("Please ensure you are not reprocessing the same batch unless intended.\n")

print(f"Batch to be processed next: {n}")
print(f"Batches already processed: {lastprocessedbatch:,} / {total_batches:,} batches")
print(f"Batches to process: {total_batches - n}")
print(f"Batch size: {batch_size:,} articles")
print(f"Total batches of dataset: {total_batches:,}")

Batch to be processed next: 1
Batches already processed: 0 / 4 batches
Batches to process: 3
Batch size: 4,000 articles
Total batches of dataset: 4

In [17]:
print(f"Processing Batch {n}/{total_batches}...")

# Run classification on batch data
os.chdir(classifier_directory)
start_time = time.time()

gc.classify_table(dataset=f"subset_df_gccolumn_batch_{n}", withEvaluation=False, constrainedOutput=True) #Need to define the CSV!
# withEvaluation=False if not done manually
print("\n\nSuccess!")
print("File saved as subset_df_gccolumn_batch_n_(restuls)!")

# Get end timestamp
end_time = time.time()
runtime_duration = end_time - start_time

##############

# Generate output
output_filename = f"Study_design_classification_runtime_subset_data_batch_{n}.txt"
lastprocessedbatch=n

# Convert runtime to minutes and hours
runtime_minutes = runtime_duration / 60
runtime_hours = runtime_duration / 3600

print(f"\n ######### Batch {n} Runtime Summary: ########")
print(f"- Start Time: {time.ctime(start_time)}")
print(f"- End Time: {time.ctime(end_time)}")
print(f"- Total Runtime: {runtime_duration:.4f} seconds | {runtime_minutes:.2f} minutes | {runtime_hours:.2f} hours")

with open(output_filename, "w") as f:
    f.write(f"Start Time: {time.ctime(start_time)}\n")
    f.write(f"End Time: {time.ctime(end_time)}\n")
    f.write(f"Total Runtime (seconds): {runtime_duration:.4f}\n")
    f.write(f"Total Runtime (minutes): {runtime_minutes:.2f}\n")
    f.write(f"Total Runtime (hours): {runtime_hours:.2f}\n")

print(f"\nRuntime saved in {output_filename}\n")

Processing Batch 1/3...
Processed 100/4998 rows (2.00%)

KeyboardInterrupt:

### Update-AB: Batch multithreading

In [ ]:
# Update-AB: Batch multithreading 

import os
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

max_workers = 4

def process_batch(n):

    dataset_name = f"subset_df_gccolumn_batch_{n}"
    dataset_path = os.path.join(classifier_directory, dataset_name + ".csv")

    if not os.path.exists(dataset_path):
        raise FileNotFoundError(dataset_path)

    print(f"Processing Batch {n}/{total_batches}...")

    start_time = time.time()

    # ⭐ VERY IMPORTANT — instantiate inside thread
    # Replace with your actual client constructor if needed
    # gc_local = GuardrailsClient(...)
    gc_local = gc

    gc_local.classify_table(
        dataset=dataset_name,   # NO PATH
        withEvaluation=False,
        constrainedOutput=True
    )

    end_time = time.time()
    runtime_duration = end_time - start_time

    runtime_minutes = runtime_duration / 60
    runtime_hours = runtime_duration / 3600

    output_filename = os.path.join(
        output_directory,
        f"Study_design_classification_runtime_subset_data_batch_{n}.txt"
    )

    with open(output_filename, "w") as f:
        f.write(f"Start Time: {time.ctime(start_time)}\n")
        f.write(f"End Time: {time.ctime(end_time)}\n")
        f.write(f"Total Runtime (seconds): {runtime_duration:.4f}\n")
        f.write(f"Total Runtime (minutes): {runtime_minutes:.2f}\n")
        f.write(f"Total Runtime (hours): {runtime_hours:.2f}\n")

    print(f"\n✅ Batch {n} finished")
    print(f"Runtime: {runtime_minutes:.2f} minutes")
    print(f"Log saved → {output_filename}\n")

    return n, runtime_duration

overall_start = time.time()

with ThreadPoolExecutor(max_workers=max_workers) as executor:

    futures = [executor.submit(process_batch, n)
               for n in range(1, total_batches + 1)]

    for future in as_completed(futures):
        batch_id, runtime = future.result()
        print(f"✔ Completed batch {batch_id}")

overall_end = time.time()

print("\n==============================")
print("ALL BATCHES COMPLETE")
print(f"Total wall time: {(overall_end - overall_start)/60:.2f} minutes")
print("==============================")

Processing Batch 1/4...
Processing Batch 2/4...
Processing Batch 3/4...
Processing Batch 4/4...
Processed 100/2500 rows (4.00%)
Processed 100/4000 rows (2.50%)
Processed 100/3999 rows (2.50%)
Processed 100/3999 rows (2.50%)
Processed 200/4000 rows (5.00%)
Processed 200/3999 rows (5.00%)
Processed 200/2500 rows (8.00%)
Processed 200/3999 rows (5.00%)
Processed 300/4000 rows (7.50%)
Processed 300/3999 rows (7.50%)
Processed 300/3999 rows (7.50%)
Processed 300/2500 rows (12.00%)

BadRequestError: Error code: 400 - {'error': {'message': 'CUDA out of memory. Tried to allocate 416.00 MiB. GPU 0 has a total capacity of 79.18 GiB of which 280.69 MiB is free. Process 3238203 has 588.00 MiB memory in use. Process 3242223 has 78.31 GiB memory in use. 37.18 GiB allowed; Of the allocated memory 36.01 GiB is allocated by PyTorch, with 282.00 MiB allocated in private pools (e.g., CUDA Graphs), and 886.54 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)'}}

In [15]:
# Create total runtime calculation

# Initialize total runtime accumulator
total_cumulative_seconds = 0

# Loop through all batch files up to total_batches
for n in range(1, total_batches + 1):
    filename = f"Study_design_classification_runtime_subset_data_batch_{n}.txt"
    file_path = os.path.join(classifier_directory, filename)

    # Check if the file exists, otherwise skip
    if not os.path.exists(file_path):
        print(f"Skipping missing file: {filename}")
        continue

    # Read the file and extract runtime in seconds
    with open(file_path, "r") as f:
        for line in f:
            if "Total Runtime (seconds):" in line:
                runtime_seconds = float(line.strip().split(":")[1])
                total_cumulative_seconds += runtime_seconds
                break

# Convert total runtime to minutes and hours
total_cumulative_minutes = total_cumulative_seconds / 60
total_cumulative_hours = total_cumulative_seconds / 3600

print(f"\nTotal cumulative runtime of general calssifier for study categorization:")
print(f"Seconds: {total_cumulative_seconds:.4f}")
print(f"Minutes: {total_cumulative_minutes:.2f}")
print(f"Hours: {total_cumulative_hours:.2f}")

Skipping missing file: Study_design_classification_runtime_subset_data_batch_1.txt
Skipping missing file: Study_design_classification_runtime_subset_data_batch_2.txt
Skipping missing file: Study_design_classification_runtime_subset_data_batch_3.txt
Skipping missing file: Study_design_classification_runtime_subset_data_batch_4.txt

Total cumulative runtime of general calssifier for study categorization:
Seconds: 0.0002
Minutes: 0.00
Hours: 0.00

# ==============================

## 4) Merge batch dataframes

In [ ]:
print("Number of total batches:", total_batches)
os.chdir(classifier_directory)

#total_batches = 8

for n in range(1, total_batches + 1):
    #input_filename = f"subset_df_gccolumn_batch_{n}_(result).csv"
    input_filename = f"chunk_{n}_(result).csv" # Update-AB: for the chunks logic instead of batches
    output_filename = f"fixed_output_batch_{n}.csv"

    # Check if the file exists, if not, skip it
    if not os.path.exists(input_filename):
        print(f"Batch {n}: File not found. Skipping...")
        continue

    try:
        # Read the file while forcing a semicolon separator
        df = pd.read_csv(input_filename, sep=";", engine="python")

        # Save it back properly as a CSV with commas as delimiters
        df.to_csv(output_filename, index=False, sep=",", quoting=1)

        # Read again, fix delimiters, rename columns, and save in one go
        df.rename(columns={df.columns[0]: "PaperId,PaperTitle_and_Abstracts", 
                           df.columns[1]: "Study_design"}, inplace=True)
        df.to_csv(output_filename, index=False, sep=",", quoting=1)

    except Exception as e:
        print(f"Batch {n}: Error processing file - {e}")

print("\nProcessing complete for all available batches!")

file_1 = "fixed_output_batch_1.csv"
if os.path.exists(file_1):
    print(pd.read_csv(file_1).head(5))
else:
    print("\nBatch 1 is not available yet.")

Number of total batches: 4

Processing complete for all available batches!
   PaperId,PaperTitle_and_Abstracts  \
0                                 1
1                                 2
2                                 3
3                                 4
4                                 5

                                        Study_design            Study Type  \
0  7119160011,"Screening and biological function ...       In silico study
1  7125210125,"FBXO9 promotes anti-tumor immunity...  In vivo/Animal study
2  7125273960,"The miR-142-5p overexpression indu...        In vitro study
3  7124886525,"Kita-Kyushu lung cancer antigen-1 ...        Clinical study
4  7124927607,"Identification of endogenous refer...        In vitro study

  Probability
0           -
1           -
2           -
3           -
4           -

In [ ]:
# Merge the batches
merged_df_list = []

for n in range(1, total_batches + 1):
    file_name = f"fixed_output_batch_{n}.csv"
    
    if os.path.exists(file_name):
        df = pd.read_csv(file_name)
        merged_df_list.append(df)
        print(f"Batch {n} added to merge with {len(df)} rows.")
    else:
        print(f"Batch {n} is missing. Skipping...")

# Merge all available DataFrames
final_merged_gc_df = pd.concat(merged_df_list, ignore_index=True)
final_merged_gc_df.to_csv("final_merged_gc_output.csv", index=False, sep=",", quoting=1)
print(f"\nFinal merged dataset saved as 'final_merged_gc_output.csv' with {len(final_merged_gc_df)} total rows.")
print(final_merged_gc_df)

Batch 0 added to merge with 1813 rows.
Batch 1 added to merge with 1812 rows.
Batch 2 added to merge with 1813 rows.
Batch 3 added to merge with 1812 rows.
Batch 4 added to merge with 1812 rows.
Batch 5 added to merge with 1812 rows.
Batch 6 added to merge with 1812 rows.
Batch 7 added to merge with 1812 rows.

Final merged dataset saved as 'final_merged_gc_output.csv' with 14498 total rows.
       PaperId,PaperTitle_and_Abstracts  \
0                                     1
1                                     2
2                                     3
3                                     4
4                                     5
...                                 ...
14493                              1808
14494                              1809
14495                              1810
14496                              1811
14497                              1812

                                            Study_design  \
0      7106250716,"PVNDMVLiver Circuit Drives Hepatoc...
1      7125201640,"Clinicopathological Factors on Sur...
2      7125263113,"SIAH2WNK1 Signaling Drives Glycoly...
3      7124882620,"B021: Modeling Human Immune Compet...
4      7124922374,"Evaluation of agmatines anti-cance...
...                                                  ...
14493  7116128796,"Expression of endothelin-1 in unaf...
14494  7117235300,"Time-dependent exposure to venetoc...
14495  7118161155,"USP3 Promotes Glioma Progression b...
14496  7120596868,"Translational study of IL-33 expre...
14497  7124137038,"Diagnostic Utility of Claudin-1 an...

                    Study Type Probability
0         In vivo/Animal study           -
1               Clinical study           -
2               In vitro study           -
3         In vivo/Animal study           -
4               In vitro study           -
...                        ...         ...
14493           Clinical study           -
14494           In vitro study           -
14495           In vitro study           -
14496           Clinical study           -
14497  Observational/RWE study           -

[14498 rows x 4 columns]

In [ ]:
# Split classifier output columns and prepare GC dataset
os.chdir(classifier_directory)

# Update-AB: fix header if it has problems
#merged_df = pd.read_csv("final_merged_gc_output.csv")
merged_df = pd.read_csv("final_merged_gc_output.csv", header=None, skiprows=1,
                        names=['index', 'PaperId,PaperTitle_and_Abstracts', 'Study_design', 'Study Type', 'Probability'])
merged_df = merged_df.drop(columns=['index'])

print("**Merged batches of GC dataset:**")
print(merged_df)

merged_df[['PaperId', 'PaperTitle_and_Abstracts']] = merged_df['PaperId,PaperTitle_and_Abstracts'].str.split(',', n=1, expand=True)
merged_df['PaperId'] = merged_df['PaperId'].str.strip('"').astype(int)
merged_df.drop(columns=['PaperId,PaperTitle_and_Abstracts', 'PaperTitle_and_Abstracts'], inplace=True)

print("\n\n**Merged batches of GC dataset after splitting and dropping PaperTitle and Abstract columns:**")
print(merged_df)
#article_df['PaperId'] = article_df['PaperId'].astype(int) Update-AB: article_df does not exist, fix below with merged_df
merged_df['PaperId'] = merged_df['PaperId'].astype(int)
print("\n\n-->Success!")
gclength = len(merged_df)
output_filename = f"corrected_classification_gc_output_{gclength}.csv"
merged_df.to_csv(output_filename, index=False)

print(merged_df)
print(f"\nLength of merged gc dataset: {gclength}")
print(f"Final file saved as: {output_filename}")

**Merged batches of GC dataset:**
                        PaperId,PaperTitle_and_Abstracts  \
0      7106250716,"PVNDMVLiver Circuit Drives Hepatoc...
1      7125201640,"Clinicopathological Factors on Sur...
2      7125263113,"SIAH2WNK1 Signaling Drives Glycoly...
3      7124882620,"B021: Modeling Human Immune Compet...
4      7124922374,"Evaluation of agmatines anti-cance...
...                                                  ...
14493  7116128796,"Expression of endothelin-1 in unaf...
14494  7117235300,"Time-dependent exposure to venetoc...
14495  7118161155,"USP3 Promotes Glioma Progression b...
14496  7120596868,"Translational study of IL-33 expre...
14497  7124137038,"Diagnostic Utility of Claudin-1 an...

                  Study_design Study Type  Probability
0         In vivo/Animal study          -          NaN
1               Clinical study          -          NaN
2               In vitro study          -          NaN
3         In vivo/Animal study          -          NaN
4               In vitro study          -          NaN
...                        ...        ...          ...
14493           Clinical study          -          NaN
14494           In vitro study          -          NaN
14495           In vitro study          -          NaN
14496           Clinical study          -          NaN
14497  Observational/RWE study          -          NaN

[14498 rows x 4 columns]


**Merged batches of GC dataset after splitting and dropping PaperTitle and Abstract columns:**
                  Study_design Study Type  Probability     PaperId
0         In vivo/Animal study          -          NaN  7106250716
1               Clinical study          -          NaN  7125201640
2               In vitro study          -          NaN  7125263113
3         In vivo/Animal study          -          NaN  7124882620
4               In vitro study          -          NaN  7124922374
...                        ...        ...          ...         ...
14493           Clinical study          -          NaN  7116128796
14494           In vitro study          -          NaN  7117235300
14495           In vitro study          -          NaN  7118161155
14496           Clinical study          -          NaN  7120596868
14497  Observational/RWE study          -          NaN  7124137038

[14498 rows x 4 columns]


-->Success!
                  Study_design Study Type  Probability     PaperId
0         In vivo/Animal study          -          NaN  7106250716
1               Clinical study          -          NaN  7125201640
2               In vitro study          -          NaN  7125263113
3         In vivo/Animal study          -          NaN  7124882620
4               In vitro study          -          NaN  7124922374
...                        ...        ...          ...         ...
14493           Clinical study          -          NaN  7116128796
14494           In vitro study          -          NaN  7117235300
14495           In vitro study          -          NaN  7118161155
14496           Clinical study          -          NaN  7120596868
14497  Observational/RWE study          -          NaN  7124137038

[14498 rows x 4 columns]

Length of merged gc dataset: 14498
Final file saved as: corrected_classification_gc_output_14498.csv

In [12]:
# Load  full dataset for merging
os.chdir(output_directory)
print("\nCurrent Working Directory:", os.getcwd())
cancer_df = pd.read_csv("binary_cancer_matrix_filtered.csv")
len_cancer_df=len(cancer_df)
print(f" --> Total rows in cancer dataset: {len_cancer_df:,}")
cancer_df = cancer_df[['PaperId', 'PaperTitle', 'Abstract']].copy()
print(f" --> Reconfirmed: Total rows in cancer dataset: {len_cancer_df:,}")
print("--> Full cancer dataset loaded!")
os.chdir(classifier_directory)
print("\nCurrent Working Directory:", os.getcwd())

Current Working Directory: /Users/andreiblindu/Desktop/Idiap/code/Variantscape/results_openalex/04_categorization
 --> Total rows in cancer dataset: 14,500
 --> Reconfirmed: Total rows in cancer dataset: 14,500
--> Full cancer dataset loaded!

Current Working Directory: /Users/andreiblindu/Desktop/Idiap/code/Variantscape/results_openalex/04_03_classifier

In [34]:
# Merge classified dataset with cancer terms and save final output
os.chdir(classifier_directory)
print("\nCurrent Working Directory:", os.getcwd())
start_time = time.time()
total_rows = len(merged_df)
with tqdm(total=total_rows, desc="Merging Data", unit="rows") as pbar:
    full_merged_df = merged_df.merge(cancer_df, on="PaperId", how="left", indicator=True)
    pbar.update(total_rows)
end_time = time.time()
execution_time = end_time - start_time
successful_matches = full_merged_df['_merge'].value_counts().get('both', 0)
failed_matches = full_merged_df['_merge'].value_counts().get('left_only', 0)
full_merged_df.drop(columns=['_merge'], inplace=True)
full_merged_df.to_csv("full_merged_output_after_classification.csv", index=False)
full_length = len(full_merged_df)
output_filename = f"final_gc_classificaton_output_{full_length}.csv"
full_merged_df.to_csv(output_filename, index=False)

print(f"Total Entries in merged_df: {len(merged_df)}")
print(f"Successful Matches: {successful_matches}")
print(f"Unmatched Entries: {failed_matches}")
print(f"Execution Time: {execution_time:.2f} seconds")
print(f"Final file saved as: {output_filename}")
print(f"Total rows in final dataset: {full_length}")

Current Working Directory: /Users/andreiblindu/Desktop/Idiap/code/Variantscape/results_openalex/04_03_classifier

Merging Data: 100%|██████████| 14498/14498 [00:00<00:00, 458382.48rows/s]

Total Entries in merged_df: 14498
Successful Matches: 14498
Unmatched Entries: 0
Execution Time: 0.06 seconds
Final file saved as: final_gc_classificaton_output_14498.csv
Total rows in final dataset: 14498

## Debug

In [13]:
set(cancer_df['PaperId']).difference(set(merged_df['PaperId']))

{4416139686, 7110785213}

In [15]:
diff_df = cancer_df[cancer_df['PaperId'].isin([4416139686, 7110785213])]
diff_df

,PaperId,PaperTitle,Abstract
2873,4416139686,TMIC-52. Clinical correlates of the diffuse gl...,BACKGROUND Glioma progression and invasion is ...
5003,7110785213,"Orginal western blot data of Figs 1, 2, 3 and 4.",Zinc Finger and BTB Domain-containing7A (ZBTB7...

In [17]:
dataset_name = f"diff_df"
diff_df.to_csv(dataset_name + ".csv", index=False)

gc.classify_table(
    dataset=dataset_name,
    withEvaluation=False,
    constrainedOutput=True
)

Processed 2/2 rows (100.00%)
Classification of 'diff_df.csv' complete. Output written to 'diff_df_(result).csv'.
Elapsed time: 3.82 seconds

In [21]:
pd.read_csv('diff_df_(result).csv', sep=';')

,Unnamed: 0,Text,Study Type,Probability
0,1,"4416139686,TMIC-52. Clinical correlates of the...",Systematic review study,-
1,2,"7110785213,""Orginal western blot data of Figs ...",In vitro study,-